name: blog.nickesselman.nl
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog.nickesselman.nl:prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOST: "0.0.0.0"
    ports:
      - "127.0.0.1:3013:3000"
    working_dir: /app
